  configs:
    ups.conf:
      content: |
        [ups]
        driver = usbhid-ups
        # Documentation: https://networkupstools.org/docs/man/usbhid-ups.html#_extra_arguments
        port = auto
        desc = "ups"
        lbrb_log_delay_without_calibrating = 1
        onlinedischarge_calibration = 1
        lbrb_log_delay_sec = 4
    # 3493 is the default port for TrueNAS to connect to NUT, ensure it matches your setting
    upsd.conf:
      content: |
        LISTEN * 3493
    # password and user required for TrueNAS to connect, ensure it matches your settings and 
    # add additional users if you desired
    upsd.users:
      content: |
        [upsmon]
        password = ups12345
        upsmon master
  services:
    nut:
      build:
        # If you change the version here, be sure to change the version below (Image:) Otherwise,
        # it will not rebuild
        dockerfile_inline: |
          FROM alpine:3.23
          ARG NUT_VERSION=v2.8.5
          RUN apk add --no-cache --virtual .build-deps \
                  autoconf \
                  automake \
                  git \
                  perl \
                  python3 \
                  libtool \
                  g++ \
                  libmodbus-dev \
                  libusb-dev \
                  make \
                  neon-dev \
                  net-snmp-dev \
                  nss-dev && \
            git clone --branch $${NUT_VERSION} https://github.com/networkupstools/nut /root/nut && \
            cd /root/nut && \
            ./autogen.sh && \
            ./configure --prefix=/usr --libexecdir=/usr/lib/nut \
              --without-wrap --with-user=nut --with-group=nut --disable-static --with-serial --with-usb --without-avahi --with-snmp \
              --with-modbus --with-neon --without-powerman --without-ipmi --without-freeipmi --with-libltdl --without-cgi \
              --with-drvpath=/usr/lib/nut --datadir=/usr/share/nut --sysconfdir=/etc/nut --with-statepath=/var/run/nut \
              --with-altpidpath=/var/run/nut --with-udev-dir=/usr/lib/udev --with-nss --with-openss && \
            make -j "$(nproc)" all && \
            make install && \
            mkdir /var/run/nut && \
            apk del --no-network .build-deps && \
            rm -rf /root/nut
          RUN apk add \
                  ca-certificates \
                  eudev \
                  eudev-libs \
                  hidapi \
                  kmod-libs \
                  libblkid \
                  libeconf \
                  libexpat \
                  libgcc \
                  libltdl \
                  libmodbus \
                  libstdc++ \
                  libusb \
                  neon \
                  net-snmp-libs \
                  nspr \
                  nss \
                  nut-udev \
                  sqlite-libs \
                  udev-init-scripts \
                  udev-init-scripts-openrc \
                  xz-libs \
                  zstd-libs
          RUN addgroup -g 126 nut && adduser -H -s /sbin/nologin -u 568 -G nut -D nut && \
            chown nut:nut /var/run/nut && \
            chmod 770 /var/run/nut
          WORKDIR /root
          ENTRYPOINT ["/bin/sh", "-c", "/usr/sbin/upsdrvctl -u nut start && /usr/sbin/upsd -u nut -FF"]
      configs:
        - source: ups.conf
          target: /etc/nut/ups.conf
          uid: "0"
          gid: "126"
          mode: 0440
        - source: upsd.conf
          target: /etc/nut/upsd.conf
          uid: "0"
          gid: "126"
          mode: 0440
        - source: upsd.users
          target: /etc/nut/upsd.users
          uid: "0"
          gid: "126"
          mode: 0440
      # Some UPS devices (like my APC) randomly disconnect/reconnect resulting in the USB Device ID changing.
      # This option allows the container to dynamically update the USB device list (aka hotplug). If you don't
      # experience this problem, you can safely comment it out. If 189 is not the correct "major" number for you and
      # you do get disconnect/reconnects, see https://github.com/invario/truenas-ups-workaround#additional-info 
      # to find the right number.
      device_cgroup_rules:
        - 'c 189:* rmw'
      image: nut:truenas-workaround-2.8.5
      # Port 3493 is required to be published for the TrueNAS host to connect, do not change it
      ports:
        - host_ip: 0.0.0.0
          mode: ingress
          protocol: tcp
          published: 3493
          target: 3493
      restart: unless-stopped
      # Run as root initially with GID 126 (nut).
      user: '0:126'
      volumes:
        - source: /dev/bus/usb
          target: /dev/bus/usb
          type: bind

