name: Shellcheck
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run ShellCheck
      uses: ludeeus/shellcheck-action@master
      
  shfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install shfmt
      uses: mfinelli/setup-shfmt@v3
    - name: Check Formatting
      run: shfmt -d .
